csportal/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from main import main_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include(main_urls))
]

main/models.py
from django.db import models

class Students(models.Model) :
    rollNum = models.IntegerField()
    name =  models.CharField(max_length=20)
    branch = models.CharField(max_length=20)
    sem = models.CharField(max_length=2)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Students

# Create your views here.
def test(request) :
    return HttpResponse("<h1> welcome to cs portal </h1>")
def student(request) :
    students = Students.objects.all()
    return render(request,"index.html",{'students': students})

templates/about.html
<!DOCTYPE HTML>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>About - Zerotype Website Template</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
</head>
<body>
	<div id="header">
		<div>
			<div class="logo">
				<a href="index.html">Zero Type</a>
			</div>
			<ul id="navigation">
				<li>
					<a href="index.html">Home</a>
				</li>
				<li>
					<a href="features.html">Features</a>
				</li>
				<li>
					<a href="news.html">News</a>
				</li>
				<li class="active">
					<a href="about.html">About</a>
				</li>
				<li>
					<a href="contact.html">Contact</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="contents">
		<div id="about">
			<h1>About</h1>
			<h2>We Have Free Templates for Everyone</h2>
			<p>
				Our website templates are created with inspiration, checked for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You can do a lot with them. You can modify them. You can use them to design websites for clients, so long as you agree with the <a href="http://www.freewebsitetemplates.com/about/terms/">Terms of Use</a>. You can even remove all our links if you want to.
			</p>
			<h2>We Have More Templates for You</h2>
			<p>
				Looking for more templates? Just browse through all our <a href="http://www.freewebsitetemplates.com/">Free Website Templates</a> and find what you're looking for. But if you don't find any website template you can use, you can try our <a href="http://www.freewebsitetemplates.com/freewebdesign/">Free Web Design</a> service and tell us all about it. Maybe you're looking for something different, something special. And we love the challenge of doing something different and something special.
			</p>
			<h2>Be Part of Our Community</h2>
			<p>
				If you're experiencing issues and concerns about this website template, join the discussion <a href="http://www.freewebsitetemplates.com/forums/">on our forum</a> and meet other people in the community who share the same interests with you.
			</p>
			<h2>Template details</h2>
			<p>
				Design version 9<br> Code version 3<br> Website Template details, discussion and updates for this <a href="http://www.freewebsitetemplates.com/discuss/zerotype/">Zerotype Website Template</a>.<br> Website Template design by <a href="http://www.freewebsitetemplates.com/">Free Website Templates</a>.<br> Please feel free to remove some or all the text and links of this page and replace it with your own About content.
			</p>
		</div>
	</div>
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a><a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a><a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a><a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				© 2023 Zerotype. All Rights Reserved.
			</p>
		</div>
	</div>
</body>
</html>

templates/contact.html
<!DOCTYPE HTML>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>Contact - Zerotype Website Template</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
</head>
<body>
	<div id="header">
		<div>
			<div class="logo">
				<a href="index.html">Zero Type</a>
			</div>
			<ul id="navigation">
				<li>
					<a href="index.html">Home</a>
				</li>
				<li>
					<a href="features.html">Features</a>
				</li>
				<li>
					<a href="news.html">News</a>
				</li>
				<li>
					<a href="about.html">About</a>
				</li>
				<li class="active">
					<a href="contact.html">Contact</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="contents">
		<div class="section">
			<h1>Contact</h1>
			<p>
				You can replace all this text with your own text. Want an easier solution for a Free Website? Head straight to Wix and immediately start customizing your website! Wix is an online website builder with a simple drag & drop interface, meaning you do the work online and instantly publish to the web. All Wix templates are fully customizable and free to use. Just pick one you like, click Edit, and enter the online editor.
			</p>
			<form action="index.html" method="post" class="message">
				<input type="text" value="Name" onFocus="this.select();" onMouseOut="javascript:return false;"/>
				<input type="text" value="Email" onFocus="this.select();" onMouseOut="javascript:return false;"/>
				<input type="text" value="Subject" onFocus="this.select();" onMouseOut="javascript:return false;"/>
				<textarea></textarea>
				<input type="submit" value="Send"/>
			</form>
		</div>
		<div class="section contact">
			<p>
				For Inquiries Please Call: <span>877-433-8137</span>
			</p>
			<p>
				Or you can visit us at: <span>ZeroType<br> 250 Business ParK Angel Green, Sunville 109935</span>
			</p>
		</div>
	</div>
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a><a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a><a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a><a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				© 2023 Zerotype. All Rights Reserved.
			</p>
		</div>
	</div>
</body>
</html>

templates/features.html
<!DOCTYPE HTML>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>Features - Zerotype Website Template</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
</head>
<body>
	<div id="header">
		<div>
			<div class="logo">
				<a href="index.html">Zero Type</a>
			</div>
			<ul id="navigation">
				<li>
					<a href="index.html">Home</a>
				</li>
				<li class="active">
					<a href="features.html">Features</a>
				</li>
				<li>
					<a href="news.html">News</a>
				</li>
				<li>
					<a href="about.html">About</a>
				</li>
				<li>
					<a href="contact.html">Contact</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="contents">
		<div class="features">
			<h1>Features</h1>
			<p>
				Change, add, and remove items as you like. If you're having problems editing this website template, then don't hesitate to ask for help on the Forums.
			</p>
			<div>
				<img src="images/recycle.png" alt="Img">
				<h2>Customizable and Easy</h2>
				<p>
					You can replace all this text with your own text. Want an easier solution for a Free Website? Head straight to Wix and immediately start customizing your website!
				</p>
				<h2>Online in an Instant</h2>
				<p>
					Wix is an online website builder with a simple drag & drop interface, meaning you do the work online and instantly publish to the web. All Wix templates are fully customizable and free to use. Just pick one you like, click Edit, and enter the online editor.
				</p>
			</div>
			<div>
				<img src="images/box-of-icons.png" alt="Img">
				<h2>More Design Elements</h2>
				<p>
					Wix also offers a ton of free design elements right inside the editor, like images, icons, galleries, videos and large selection of Add Ons and social feeds.
				</p>
				<h2>Free to Use</h2>
				<p>
					Publish your Free Website in minutes! You can remove any link to our website from this website template, you're free to use this website template without linking back to us.
				</p>
			</div>
		</div>
	</div>
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a><a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a><a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a><a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				© 2023 Zerotype. All Rights Reserved.
			</p>
		</div>
	</div>
</body>
</html>

templates/forms.html
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>Change students | Django site admin</title>
<link rel="stylesheet" type="text/css" href="css/base.css" />
<link rel="stylesheet" type="text/css" href="css/forms.css" />

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" app-main model-students change-form"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>
        
        
        <div id="user-tools">
            
                Welcome,
                <strong>shasin</strong>.
            
            
                
                    <a href="/">View site</a> /
                
                
                    
                    
                
                
                <a href="/admin/password_change/">Change password</a> /
                
                <a href="/admin/logout/">Log out</a>
            
        </div>
        
        
        
    </div>
    <!-- END Header -->
    
<div class="breadcrumbs">
<a href="/admin/">Home</a>
&rsaquo; <a href="/admin/main/">Main</a>
&rsaquo; <a href="/admin/main/students/">Studentss</a>
&rsaquo; Students object
</div>

    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        <h1>Change students</h1>
        <div id="content-main">


  <ul class="object-tools">
    
    <li>
        
        <a href="/admin/main/students/4/history/" class="historylink">History</a>
    </li>
    
    
  </ul>


<form enctype="multipart/form-data" action="" method="post" id="students_form" novalidate><input type='hidden' name='csrfmiddlewaretoken' value='csSJEAkZMDQzAxqzXmHrU2AAhYXnEuiZSPluY5f6PlmcXFbiMsTMs9VoyAKL77iO' />
<div>







  <fieldset class="module aligned ">
    
    
    
        <div class="form-row field-rollNum">
            
            
                <div>
                    
                    
                        <label class="required" for="id_rollNum">RollNum:</label>
                        
                            <input class="vIntegerField" id="id_rollNum" name="rollNum" type="text" value="3" required />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-name">
            
            
                <div>
                    
                    
                        <label class="required" for="id_name">Name:</label>
                        
                            <input class="vTextField" id="id_name" maxlength="20" name="name" type="text" value="arfad" required />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-branch">
            
            
                <div>
                    
                    
                        <label class="required" for="id_branch">Branch:</label>
                        
                            <input class="vTextField" id="id_branch" maxlength="20" name="branch" type="text" value="CSE" required />
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-sem">
            
            
                <div>
                    
                    
                        <label class="required" for="id_sem">Sem:</label>
                        
                            <input class="vTextField" id="id_sem" maxlength="2" name="sem" type="text" value="s1" required />
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>













<div class="submit-row">
<input type="submit" value="Save" class="default" name="_save" />

    
    <p class="deletelink-box"><a href="/admin/main/students/4/delete/" class="deletelink">Delete</a></p>


<input type="submit" value="Save and add another" name="_addanother" />
<input type="submit" value="Save and continue editing" name="_continue" />
</div>



    <script type="text/javascript"
            id="django-admin-form-add-constants"
            src="/static/admin/js/change_form.js"
            >
    </script>




<script type="text/javascript"
        id="django-admin-prepopulated-fields-constants"
        src="/static/admin/js/prepopulate_init.js"
        data-prepopulated-fields="[]">
</script>


</div>
</form></div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

templates/index.html
<html>
<head>
	<meta charset="UTF-8">
	<title>Welcome to Cs portal</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}"  type="text/css">
</head>
<body>
	<div id="header">
		<div>
			<div class="logo">
				<a href="index.html">CS Portal</a>
			</div>
			<ul id="navigation">
				<li class="active">
					<a href="index.html">Home</a>
				</li>
				<li>
					<a href="features.html">Features</a>
				</li>
				<li>
					<a href="news.html">News</a>
				</li>
				<li>
					<a href="about.html">About</a>
				</li>
				<li>
					<a href="contact.html">Contact</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="adbox">
		<div class="clearfix">
			
			<img src="" alt="Img" height="342" width="368">
			<div>
				<h1>Learn And Explore</h1>
				<h2>Computer Science Portal</h2>
				<p>
					CS portal is an online platform which helps KTU B-Tech Computer Science and Engineering Students to learn and explore different
					Programming Languages,Databases,Web Technologies and more Sign up to continue !!
					 <span><a href="login.html" class="btn">Sign Up Now!</a><b>Don’t worry it’s for free</b></span>
				</p>
			</div>
		</div>
	</div>
	<div id="contents">
		<div id="tagline" class="clearfix">
			<h1>Design With Simplicity.</h1>
			<div>
				<p>
					You can replace all this text with your own text. Want an easier solution for a Free Website?
				</p>
				<p>
					Head straight to Wix and immediately start customizing your website!
				</p>
				<p>
					Wix is an online website builder with a simple drag & drop interface, meaning you do the work online and instantly publish to the web.
				</p>
			</div>
			<div>
				<p>
					You can replace all this text with your own text. Want an easier solution for a Free Website?
				</p>
				<p>
					Head straight to Wix and immediately start customizing your website!
				</p>
				<p>
					Wix is an online website builder with a simple drag & drop interface, meaning you do the work online and instantly publish to the web.
				</p>
			</div>
		</div>
	</div>
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a><a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a><a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a><a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				© 2023 Zerotype. All Rights Reserved.
			</p>
		</div>
	</div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en-us" >
<head>
<title>Log in | Django site admin</title>
<link rel="stylesheet" type="text/css" href="css/base.css" />
<link rel="stylesheet" type="text/css" href="css/login.css" />




<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" login"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>
        
        
    </div>
    <!-- END Header -->
    
    

    
        
    

    <!-- Content -->
    <div id="content" class="colM">
        
        
        




<div id="content-main">



<form action="/admin/login/?next=/admin/" method="post" id="login-form"><input type='hidden' name='csrfmiddlewaretoken' value='RqMidk7yieUOBohjA1gyRAKEKffst96MsCJK7cewRQNEAlER13nvu6PFDNiZCXMl' />
  <div class="form-row">
    
    <label class="required" for="id_username">Username:</label> <input autofocus="" id="id_username" maxlength="254" name="username" type="text" required />
  </div>
  <div class="form-row">
    
    <label class="required" for="id_password">Password:</label> <input id="id_password" name="password" type="password" required />
    <input type="hidden" name="next" value="/admin/" />
  </div>
  
  
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Log in" />
  </div>
</form>

</div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

templates/news.html
<!DOCTYPE HTML>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>News - Zerotype Website Template</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
</head>
<body>
	<div id="header">
		<div>
			<div class="logo">
				<a href="index.html">Zero Type</a>
			</div>
			<ul id="navigation">
				<li>
					<a href="index.html">Home</a>
				</li>
				<li>
					<a href="features.html">Features</a>
				</li>
				<li class="active">
					<a href="news.html">News</a>
				</li>
				<li>
					<a href="about.html">About</a>
				</li>
				<li>
					<a href="contact.html">Contact</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="contents">
		<div class="main">
			<h1>News</h1>
			<ul class="news">
				<li>
					<div class="date">
						<p>
							<span>03</span>
							2023
						</p>
					</div>
					<h2>Updates: More Features Released <span>Brian Ferry</span></h2>
					<p>
						You can replace all this text with your own text. Want an easier solution for a Free Website? Head straight to Wix and immediately start customizing your website! Wix is an online website builder with a simple drag &amp; drop interface, meaning you do the work online and instantly publish to the web. All Wix templates are fully customizable and free to use. Just pick one you like, click Edit, and enter the online editor. <span><a href="post.html" class="more">Read More</a></span>
					</p>
				</li>
				<li>
					<div class="date">
						<p>
							<span>03</span>
							2023
						</p>
					</div>
					<h2>Updates: More Features Released <span>Brian Ferry</span></h2>
					<p>
						You can replace all this text with your own text. Want an easier solution for a Free Website? Head straight to Wix and immediately start customizing your website! Wix is an online website builder with a simple drag &amp; drop interface, meaning you do the work online and instantly publish to the web. All Wix templates are fully customizable and free to use. Just pick one you like, click Edit, and enter the online editor. <span><a href="post.html" class="more">Read More</a></span>
					</p>
				</li>
				<li>
					<div class="date">
						<p>
							<span>03</span>
							2023
						</p>
					</div>
					<h2>Updates: More Features Released <span>Brian Ferry</span></h2>
					<p>
						You can replace all this text with your own text. Want an easier solution for a Free Website? Head straight to Wix and immediately start customizing your website! Wix is an online website builder with a simple drag &amp; drop interface, meaning you do the work online and instantly publish to the web. All Wix templates are fully customizable and free to use. Just pick one you like, click Edit, and enter the online editor. <span><a href="post.html" class="more">Read More</a></span>
					</p>
				</li>
			</ul>
		</div>
		<div class="sidebar">
			<h1>Popular Posts</h1>
			<ul class="posts">
				<li>
					<h4 class="title"><a href="post.html">Making It Work</a></h4>
					<p>
						I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.
					</p>
				</li>
				<li>
					<h4 class="title"><a href="post.html">Designs and Concepts</a></h4>
					<p>
						I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.
					</p>
				</li>
				<li>
					<h4 class="title"><a href="post.html">Getting It Done!</a></h4>
					<p>
						I'm a paragraph. Click here to add your own text and edit me. I’m a great place for you to tell a story and let your users know a little more about you.
					</p>
				</li>
			</ul>
		</div>
	</div>
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a><a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a><a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a><a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				© 2023 Zerotype. All Rights Reserved.
			</p>
		</div>
	</div>
</body>
</html>

templates/post.html
<!DOCTYPE HTML>
<!-- Website template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>News title - Zerotype Website Template</title>
	<link rel="stylesheet" href="css/style.css" type="text/css">
</head>
<body>
	<div id="header">
		<div>
			<div class="logo">
				<a href="index.html">Zero Type</a>
			</div>
			<ul id="navigation">
				<li>
					<a href="index.html">Home</a>
				</li>
				<li>
					<a href="features.html">Features</a>
				</li>
				<li class="active">
					<a href="news.html">News</a>
				</li>
				<li>
					<a href="about.html">About</a>
				</li>
				<li>
					<a href="contact.html">Contact</a>
				</li>
			</ul>
		</div>
	</div>
	<div id="contents">
		<div class="post">
			<div class="date">
				<p>
					<span>03</span>
					2023
				</p>
			</div>
			<h1>Updates: More Features Released <span class="author">Brian Ferry March 2012</span></h1>
			<p>
				You can replace all this text with your own text. Want an easier solution for a Free Website? Head straight to Wix and immediately start customizing your website! Wix is an online website builder with a simple drag & drop interface, meaning you do the work online and instantly publish to the web. All Wix templates are fully customizable and free to use. Just pick one you like, click Edit, and enter the online editor.
			</p>
			<p>
				Change, add, and remove items as you like. If you're having problems editing this website template, then don't hesitate to ask for help on the Forums.
			</p>
			<p>
				Wix also offers a ton of free design elements right inside the editor, like images, icons, galleries, videos and large selection of Add Ons and social feeds. Publish your Free Website in minutes! You can remove any link to our website from this website template, you're free to use this website template without linking back to us.
			</p>
			<p>
				You can replace all this text with your own text. Want an easier solution for a Free Website? Head straight to Wix and immediately start customizing your website! Wix is an online website builder with a simple drag & drop interface, meaning you do the work online and instantly publish to the web. All Wix templates are fully customizable and free to use. Just pick one you like, click Edit, and enter the online editor.
			</p>
			<p>
				Change, add, and remove items as you like. If you're having problems editing this website template, then don't hesitate to ask for help on the Forums.
			</p>
			<p>
				Wix also offers a ton of free design elements right inside the editor, like images, icons, galleries, videos and large selection of Add Ons and social feeds. Publish your Free Website in minutes! You can remove any link to our website from this website template, you're free to use this website template without linking back to us.
			</p>
			<span><a href="post.html" class="more">Back to News</a></span>
		</div>
	</div>
	<div id="footer">
		<div class="clearfix">
			<div id="connect">
				<a href="http://freewebsitetemplates.com/go/facebook/" target="_blank" class="facebook"></a><a href="http://freewebsitetemplates.com/go/googleplus/" target="_blank" class="googleplus"></a><a href="http://freewebsitetemplates.com/go/twitter/" target="_blank" class="twitter"></a><a href="http://www.freewebsitetemplates.com/misc/contact/" target="_blank" class="tumbler"></a>
			</div>
			<p>
				© 2023 Zerotype. All Rights Reserved.
			</p>
		</div>
	</div>
</body>
</html>